bookstore_app/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/index'
  #get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/index'
  get 'users/new'
  get 'users/create'
  get 'novels/index'
  get 'novels/show'
  get 'novels/new'
  get 'novels/create'
  get 'novels/update'
  get 'novels/edit'
  get 'novels/destroy'
  get 'publishers/index'
  get 'publishers/show'
  get 'publishers/new'
  get 'publishers/create'
  get 'publishers/update'
  get 'publishers/edit'
  get 'publishers/destroy'
  get 'genres/index'
  get 'genres/show'
  get 'genres/new'
  get 'genres/create'
  get 'genres/update'
  get 'genres/edit'
  get 'genres/destroy'
  get 'authors/index'
  get 'authors/show'
  get 'authors/new'
  get 'authors/create'
  get 'authors/update'
  get 'authors/edit'
  get 'authors/delete'
  get 'static_pages/home'
  root 'static_pages#home'
  get 'static_pages/about'
  get 'static_pages/contact'
  resources :books
  resources :authors
  resources :genres
  resources :publishers
  #resources :novels
  resources :novels do
    collection do
      get :search
    end
  end
  resources :users
  resources :sessions
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bookstore_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookstore_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	private
	def current_user
		@current_user ||= User.find(session[ :user_id]) if session[ :user_id]
	end
	helper_method :current_user
	def authorize
		redirect_to new_session_path, alert: 'Please Log in or Sign Up' if current_user.nil?
	end
	
end

bookstore_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

bookstore_app/app/helpers/application_helper.rb
module ApplicationHelper
end

bookstore_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

bookstore_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>BookstoreApp</title>
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>

	<body>
		<div class="container">
			<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
				<h5 class="my-0 mr-md-auto font-weight-normal"> Sheffield Bookstore </h5>
				<nav class="my-2 my-md-0 mr-md-3">
					<a class="p-2 text-dark" href="#"><%= link_to "Home", '#' %></a>
					<a class="p-2 text-dark" href="#"><%= link_to "About Us", '#' %></a>
					<a class="p-2 text-dark" href="#"><%= link_to "Contact Us", '#' %></a>
<!-- 					<a class="p-2 text-dark" href="#"><%= link_to "Add new book", new_book_path %></a> -->
					<a class="p-2 text-dark" href="#"><%= link_to "Add new novel", new_novel_path %></a>
					<a class="p-2 text-dark" href="#"><%= link_to "Novels", novels_path %></a>
					<a class="p-2 text-dark" href="#"><%= link_to "Add new author", new_author_path %></a>
					<a class="p-2 text-dark" href="#"><%= link_to "Add new genre", new_genre_path %></a>
					<a class="p-2 text-dark" href="#"><%= link_to "Add new publisher", new_publisher_path %></a>
					<a class="p-2 text-dark" href="#"><%= link_to "Create Account", new_user_path %></a>
					<% if current_user %>
						<span class="p-2 text-dark">
							<%= link_to 'Log out', session_path('active'), method: :delete %>
						</span>
						<span class="p-2 text-dark">
							<%= current_user.userid %>
						</span>
					<% else %>
						<span class="p-2 text-dark">
							<%= link_to 'Log in', new_session_path, class: "active_nav_link" %>
						</span>
					<% end %>
				</nav> 
			</div>
		</div>
		<div class="container">
			<% if notice %>
			<%= notice %>
			<% end %>
			<% if alert %>
			<%= alert %>
			<% end %>

			<%= yield %>
		</div>
	</body>
</html>

bookstore_app/app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

bookstore_app/app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

bookstore_app/app/views/static_pages/home.html.erb
<div class="container">
	<h1 class="jumbotron-heading">Album example</h1>
	<div class="container">
		<div class="row">
			<div class="col">
				<p>Lorem ipsum dolor sit amet, at nemore disputando vis. Omnis assum et sea, cu decore alterum scriptorem eos. Cum sumo natum in, vim elit audiam et. Sed ex malorum repudiare, at sale dolor nam, in eam prima moderatius eloquentiam. Vix cu modus libris voluptatibus, pro cu illum melius adipisci. Cu sea semper appellantur voluptatibus, agam tota ei usu.</p>
			</div>
			<div class="col">
				<p>Sea inani salutatus constituto ut, ei vis brute maiestatis vituperatoribus. Eu quo perfecto qualisque persecuti, ut vix nibh phaedrum, zril eleifend perpetua vis te. Ad mea prima populo electram, eum dico delectus at. Per et primis moderatius, usu an commodo sapientem. Consequat voluptaria constituam mei ei, ei vel denique accusata.</p>
			</div>
		</div>
	</div>
</div>